# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "39786d0f7304c8f981792e5bd2806e1e"
name = "Level Chart local"
handle = "level-chart-local"
application_url = "https://zip-his-outlets-excellence.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "karan-working.myshopify.com"
include_config_on_deploy = true

[access.admin]
direct_api_mode = "offline"
embedded_app_direct_api_access = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_inventory,read_locations,read_orders,read_products,write_orders,write_products"

[auth]
redirect_urls = [
  "https://zip-his-outlets-excellence.trycloudflare.com/auth/callback",
  "https://zip-his-outlets-excellence.trycloudflare.com/auth/shopify/callback",
  "https://zip-his-outlets-excellence.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
